# Generated by Django 2.2.6 on 2020-01-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20200116_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='likes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.CustomUser'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='likes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.CustomUser'),
        ),
    ]
