# Generated by Django 2.2.6 on 2020-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_auto_20200116_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='facebook.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='facebook.Profile'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='facebook.Profile'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
