# Generated by Django 2.2.6 on 2020-01-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_auto_20200116_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('friends', models.ManyToManyField(related_name='_facebookuser_friends_+', to='facebook.FacebookUser')),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='facebook.FacebookUser'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='facebook.FacebookUser'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
