# Generated by Django 2.2.6 on 2020-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20200116_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_facebookuser_friends_+', to='facebook.FacebookUser'),
        ),
    ]
